version: '3'

networks:
  server:
    driver: bridge

services:
  api.application:
    build: .
    container_name: nestjs_api
    depends_on:
      - db
    networks:
      - server
    ports:
      - 3000:3000
  
  nginx:
    image: nginx:stable
    container_name: nginx_api
    restart: "no"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - server
    
  db:
    image: postgres:11.16
    restart: "no"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      - server