GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlU2WlFQT0VHclFna0hQdHRjWUVpYiJ9.eyJpc3MiOiJodHRwczovL2FsdGF2aXN0YS1zdGFnaW5nLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJWVVk3eENYM3FBbGNLMWl4UFZRcVNZdkZjQmtpN1BtekBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9zdGFnaW5nLWFwaS5hbHRhdmlzdGFpbnZlc3QuY29tLmJyIiwiaWF0IjoxNjc1OTY2OTQzLCJleHAiOjE2NzYwNTMzNDMsImF6cCI6IlZVWTd4Q1gzcUFsY0sxaXhQVlFxU1l2RmNCa2k3UG16IiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwicGVybWlzc2lvbnMiOltdfQ.AVA1IhVeaVKu_AnF1nHyM1OI-KPDdPAEcCwJ4RYDdQGrUf6-jr1LLGkfnNeOTdRALM4lJP8YO3f7FuKK2JPTmlmOFi97IwIzB63YHv3i2--fZsprvnhofYMBkedpU5FzXuOWY-Sb3yB8BvWFwSHDk9_WEhoB1N2_iVyGNBbg51UulS3e0CbajTg_wEJWXbiHjeEyhPvq8HjuSpGxvgMvaREBIJ2B3gvcvR3MUrRYYUeqj_2p9VL0kQ6DqgKzpbMMcZQij93vptSazny701oKHVHhdnMYex5jQ_ChqGPSSS5U-ILfASF7Wiuzd0poJ37N1l7fymKd3zP-m6PgJvPkgg
